apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-auth
  labels:
    type: local
spec:
  storageClassName: auth
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/mongo"
