apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-orders
  labels:
    type: local
spec:
  storageClassName: orders
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/orders"
