apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-tickets
  labels:
    type: local
spec:
  storageClassName: tickets
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp"
